#!/usr/bin/env python3
"""
PyEDR: Enterprise Endpoint Detection and Response Agent
========================================================================

An advanced, rule-based endpoint detection system designed for transparent, 
continuous monitoring of host activities. PyEDR establishes system baselines 
and analyzes behavioral indicators in real-time to detect anomalous persistence 
mechanisms, suspicious process executions, and unauthorized network communications.

Detections are rigorously mapped to the MITRE ATT&CK® framework, utilizing 
explicit, auditable logic to provide high-fidelity alerts with comprehensive 
context.

Author:  Techienerd
Scope:   Windows OS environments (Registry, Services, Scheduled Tasks). 
         Process and network telemetry collection is cross-platform.
Dependencies: psutil (pip install psutil)

Disclaimer: This software is intended strictly for authorized security auditing, 
monitoring, and defensive research on systems where explicit permission has 
been granted. It operates in user-mode and should be deployed as part of a 
defense-in-depth strategy.
"""

import argparse
import csv
import json
import os
import platform
import re
import sys
import time
import subprocess
from dataclasses import dataclass, field, asdict
from datetime import datetime
from pathlib import Path
from typing import Optional

try:
    import psutil
except ImportError:
    print("This tool requires psutil. Install with: pip install psutil")
    sys.exit(1)

IS_WINDOWS = platform.system() == "Windows"
if IS_WINDOWS:
    try:
        import winreg
    except ImportError:
        winreg = None
else:
    winreg = None


# ==============================================================================
# Console Output Configuration
# ==============================================================================

class C:
    """ANSI escape sequences for console text formatting and colorization."""
    RESET = "\033[0m"
    RED = "\033[91m"
    YELLOW = "\033[93m"
    GREEN = "\033[92m"
    CYAN = "\033[96m"
    GRAY = "\033[90m"
    BOLD = "\033[1m"
    MAGENTA = "\033[95m"

    @staticmethod
    def enable_on_windows():
        """Activates ANSI escape sequence processing on Windows terminals (cmd/PowerShell)."""
        if IS_WINDOWS:
            os.system("")  # Triggers VT100 escape processing via Win32 Console API side-effect


SEVERITY_COLOR = {
    "CRITICAL": C.RED + C.BOLD,
    "HIGH": C.RED,
    "MEDIUM": C.YELLOW,
    "LOW": C.CYAN,
    "INFO": C.GRAY,
}
SEVERITY_ORDER = {"CRITICAL": 4, "HIGH": 3, "MEDIUM": 2, "LOW": 1, "INFO": 0}


# ==============================================================================
# Data Structures
# ==============================================================================

@dataclass
class Alert:
    """
    Represents a discrete security alert generated by the detection engine.
    
    Attributes:
        timestamp: ISO-8601 formatted timestamp of the detection event.
        severity: Assessed severity level (e.g., CRITICAL, HIGH, MEDIUM, LOW, INFO).
        technique_id: Associated MITRE ATT&CK® technique identifier.
        technique_name: Associated MITRE ATT&CK® technique name.
        title: High-level summary of the detection.
        details: Granular technical details of the triggering event.
        source: The telemetry source that originated the alert (process/persistence/network).
    """
    timestamp: str
    severity: str
    technique_id: str
    technique_name: str
    title: str
    details: str
    source: str  # Originating telemetry source: 'process' | 'persistence' | 'network'

    def to_dict(self) -> dict:
        """Serializes the Alert instance to a dictionary for structured logging."""
        return asdict(self)

    def print_console(self):
        """Renders the alert to standard output with severity-appropriate ANSI color coding."""
        color = SEVERITY_COLOR.get(self.severity, C.RESET)
        print(f"{color}[{self.severity}] {self.technique_id} {self.technique_name}{C.RESET}")
        print(f"  {C.BOLD}{self.title}{C.RESET}")
        print(f"  {C.GRAY}{self.details}{C.RESET}")
        print(f"  {C.GRAY}@ {self.timestamp}{C.RESET}\n")


# ==============================================================================
# Detection Signatures & Heuristics (MITRE ATT&CK®)
# ==============================================================================
# The following signatures and behavioral patterns are mapped directly to 
# MITRE ATT&CK® techniques. They provide transparent, deterministic evaluation 
# criteria for the detection engine to ensure high-fidelity alerting.

SUSPICIOUS_PATH_PATTERNS = [
    re.compile(r"\\AppData\\Local\\Temp\\", re.I),
    re.compile(r"\\Users\\Public\\", re.I),
    re.compile(r"\\Windows\\Temp\\", re.I),
    re.compile(r"\\ProgramData\\(?!Microsoft)", re.I),
    re.compile(r"\\\$Recycle\.Bin\\", re.I),
]

SYSTEM_PROCESS_EXPECTED_DIR = {
    "svchost.exe": r"\windows\system32",
    "csrss.exe": r"\windows\system32",
    "lsass.exe": r"\windows\system32",
    "winlogon.exe": r"\windows\system32",
    "services.exe": r"\windows\system32",
    "explorer.exe": r"\windows",
    "smss.exe": r"\windows\system32",
    "spoolsv.exe": r"\windows\system32",
}

RAT_PROCESS_NAMES = [
    "teamviewer", "anydesk", "vncserver", "winvnc", "tvnserver", "ammyy",
    "supremo", "quickassist", "ultraviewer", "remoteutilities", "dwservice",
    "ngrok", "radmin", "logmein", "splashtop", "gotomypc", "showmypc",
    "netsupport",
]

CREDENTIAL_ACCESS_TOOL_NAMES = [
    "mimikatz", "procdump", "pwdump", "gsecdump", "wce", "lazagne",
]

LOLBIN_DOWNLOAD_INDICATORS = ["certutil", "bitsadmin", "curl", "wget"]

# Parent-child process relationships indicative of Living-off-the-Land (LotL) 
# techniques or macro-based malware execution (e.g., Office applications 
# initiating command shells or scripting interpreters).
SUSPICIOUS_PARENT_CHILD = {
    "winword.exe": {"cmd.exe", "powershell.exe", "wscript.exe", "cscript.exe", "mshta.exe"},
    "excel.exe": {"cmd.exe", "powershell.exe", "wscript.exe", "cscript.exe", "mshta.exe"},
    "outlook.exe": {"cmd.exe", "powershell.exe", "wscript.exe", "cscript.exe", "mshta.exe"},
    "powerpnt.exe": {"cmd.exe", "powershell.exe", "wscript.exe", "cscript.exe", "mshta.exe"},
    "acrord32.exe": {"cmd.exe", "powershell.exe"},
}

POWERSHELL_OBFUSCATION_FLAGS = re.compile(
    r"(-enc\b|-encodedcommand|-nop\b|-noprofile|-w(indowstyle)?\s+hidden|-ep\s+bypass|-executionpolicy\s+bypass)",
    re.I,
)

BASE64_BLOB = re.compile(r"[A-Za-z0-9+/]{80,}={0,2}")


def is_suspicious_path(path: str) -> bool:
    """
    Determines whether a given file path matches known high-risk execution directories.
    These locations are frequently leveraged by adversaries for staging or execution.

    Args:
        path: The absolute file system path of the process executable.

    Returns:
        True if the path matches a suspicious pattern, False otherwise.
    """
    if not path:
        return False
    return any(p.search(path) for p in SUSPICIOUS_PATH_PATTERNS)


def is_masquerading(name: str, path: str) -> bool:
    """
    Evaluates process execution paths against expected system directories.
    Maps to MITRE ATT&CK® T1036.005 (Masquerading: Match Legitimate Name).
    Identifies processes utilizing core Windows system names outside their designated paths.
    """
    if not path:
        return False
    expected = SYSTEM_PROCESS_EXPECTED_DIR.get(name.lower())
    if not expected:
        return False
    return expected not in path.lower()


def cmdline_str(proc_info) -> str:
    """
    Safely reconstructs a process's full command-line invocation string.
    Returns an empty string in the event of access restrictions or data unavailability.

    Args:
        proc_info: A psutil process info dictionary.

    Returns:
        The space-joined command-line string, or an empty string on failure.
    """
    try:
        cl = proc_info.get("cmdline") or []
        return " ".join(cl)
    except Exception:
        return ""


# ==============================================================================
# Core Detection Engine
# ==============================================================================

class DetectionEngine:
    """
    The primary analysis engine responsible for evaluating system telemetry 
    against defined security heuristics and signatures.
    
    The engine operates statelessly per evaluation cycle, accepting current system 
    snapshots and baseline configurations to generate corresponding Alert objects.
    """

    def __init__(self):
        self.seen_pids_flagged = set()  # Prevents duplicate alerts for previously analyzed PIDs

    def _mk(self, severity: str, tid: str, tname: str, title: str, details: str, source: str) -> Alert:
        """
        Constructs a fully-populated Alert object with a current ISO-8601 timestamp.
        This is an internal factory method used by all detection sub-routines.
        """
        return Alert(
            timestamp=datetime.now().isoformat(timespec="seconds"),
            severity=severity, technique_id=tid, technique_name=tname,
            title=title, details=details, source=source,
        )

    # ---- Process Behavioral Analysis -----------------------------------------

    def evaluate_process(self, proc_info) -> list:
        """
        Evaluates a single process snapshot against all registered process behavioral signatures.

        Args:
            proc_info: A psutil process info dictionary containing pid, ppid, name, exe, and cmdline.

        Returns:
            A list of Alert objects for all triggered detection rules. Empty list if none triggered.
        """
        alerts = []
        name = (proc_info.get("name") or "").lower()
        path = proc_info.get("exe") or ""
        pid = proc_info.get("pid")
        ppid = proc_info.get("ppid")
        cmd = cmdline_str(proc_info)
        dedup_key = f"{pid}:{name}"

        # T1036.005 Masquerading
        if is_masquerading(name, path):
            alerts.append(self._mk(
                "CRITICAL", "T1036.005", "Masquerading: Match Legitimate Name",
                f"Process '{name}' running from unexpected location",
                f"PID {pid} named '{name}' expects to run from "
                f"{SYSTEM_PROCESS_EXPECTED_DIR.get(name)}, actually at: {path}",
                "process",
            ))

        # T1036: Execution from a non-standard or adversary-controlled directory
        if is_suspicious_path(path):
            alerts.append(self._mk(
                "HIGH", "T1036", "Masquerading (suspicious execution path)",
                f"Process '{name}' executing from a non-standard path",
                f"PID {pid}, path: {path}",
                "process",
            ))

        # T1219: Remote Access Software — unauthorized remote control capability detected
        if any(r in name for r in RAT_PROCESS_NAMES):
            alerts.append(self._mk(
                "MEDIUM", "T1219", "Remote Access Software",
                f"Remote access tool running: '{name}'",
                f"PID {pid}, path: {path}. Confirm this was installed intentionally.",
                "process",
            ))

        # T1003: OS Credential Dumping — known credential extraction tool signature matched
        if any(r in name for r in CREDENTIAL_ACCESS_TOOL_NAMES):
            alerts.append(self._mk(
                "CRITICAL", "T1003", "OS Credential Dumping",
                f"Known credential-access tool detected: '{name}'",
                f"PID {pid}, path: {path}, cmdline: {cmd}",
                "process",
            ))

        # T1059.001: PowerShell invoked with known evasion or execution-policy bypass parameters
        if name == "powershell.exe" and POWERSHELL_OBFUSCATION_FLAGS.search(cmd):
            alerts.append(self._mk(
                "HIGH", "T1059.001", "Command and Scripting Interpreter: PowerShell",
                "PowerShell launched with obfuscation/bypass flags",
                f"PID {pid}, cmdline: {cmd}",
                "process",
            ))

        # T1027: High-entropy Base64 blob detected in command-line arguments, indicating payload obfuscation
        if BASE64_BLOB.search(cmd):
            alerts.append(self._mk(
                "MEDIUM", "T1027", "Obfuscated Files or Information",
                f"Long base64-like string in command line of '{name}'",
                f"PID {pid}, cmdline (truncated): {cmd[:150]}...",
                "process",
            ))

        # T1105: Living-off-the-Land Binary (LoLBin) used to initiate an outbound file transfer
        if name.replace(".exe", "") in LOLBIN_DOWNLOAD_INDICATORS and re.search(r"https?://", cmd, re.I):
            alerts.append(self._mk(
                "HIGH", "T1105", "Ingress Tool Transfer",
                f"'{name}' invoked with a URL argument (living-off-the-land download)",
                f"PID {pid}, cmdline: {cmd}",
                "process",
            ))

        # T1566/T1059: Anomalous parent-child process relationship consistent with macro-based dropper execution
        if ppid:
            try:
                parent = psutil.Process(ppid)
                pname = parent.name().lower()
                if pname in SUSPICIOUS_PARENT_CHILD and name in SUSPICIOUS_PARENT_CHILD[pname]:
                    alerts.append(self._mk(
                        "CRITICAL", "T1566/T1059", "Suspicious Parent-Child Process",
                        f"'{pname}' spawned '{name}' -- classic macro/dropper pattern",
                        f"Parent PID {ppid} ({pname}) -> Child PID {pid} ({name}), cmdline: {cmd}",
                        "process",
                    ))
            except (psutil.NoSuchProcess, psutil.AccessDenied):
                pass

        # Suppress re-alerting on the same PID to prevent alert fatigue during continuous agent polling.
        # Only return alerts for this PID if it has not been flagged previously in this session.
        if dedup_key in self.seen_pids_flagged:
            return []  # Already alerted on this PID; skip to avoid log flooding
        if alerts:
            self.seen_pids_flagged.add(dedup_key)
        return alerts

    # ---- Persistence Mechanism Analysis --------------------------------------

    def evaluate_persistence_delta(self, baseline: dict, current: dict) -> list:
        """
        Performs a differential analysis of current persistence mechanisms against 
        an established baseline. Detects modifications in registry run keys, 
        startup folders, scheduled tasks, and system services.
        """
        alerts = []

        new_run_keys = current["run_keys"] - baseline["run_keys"]
        for entry in new_run_keys:
            alerts.append(self._mk(
                "HIGH", "T1547.001", "Registry Run Keys / Startup Folder",
                "New autostart registry entry detected",
                entry, "persistence",
            ))

        new_startup = current["startup_files"] - baseline["startup_files"]
        for entry in new_startup:
            alerts.append(self._mk(
                "HIGH", "T1547.001", "Registry Run Keys / Startup Folder",
                "New file dropped in a Startup folder",
                entry, "persistence",
            ))

        new_tasks = current["scheduled_tasks"] - baseline["scheduled_tasks"]
        for entry in new_tasks:
            alerts.append(self._mk(
                "HIGH", "T1053.005", "Scheduled Task/Job: Scheduled Task",
                "New scheduled task created",
                entry, "persistence",
            ))

        new_services = current["services"] - baseline["services"]
        for entry in new_services:
            alerts.append(self._mk(
                "HIGH", "T1543.003", "Create or Modify System Process: Windows Service",
                "New auto-start service detected",
                entry, "persistence",
            ))

        return alerts

    # ---- Network Traffic Analysis --------------------------------------------

    def evaluate_network(self, conn_info) -> list:
        """
        Evaluates an active network connection against registered network behavioral signatures.

        Args:
            conn_info: A dictionary describing the connection (pid, process_name, laddr, raddr, remote_port).

        Returns:
            A list of Alert objects for all triggered detection rules. Empty list if none triggered.
        """
        alerts = []
        proc_name = (conn_info.get("process_name") or "").lower()
        remote_port = conn_info.get("remote_port")

        # Identifies unauthorized outbound network communications from processes 
        # that typically do not require network access.
        quiet_processes = {"notepad.exe", "calc.exe", "mspaint.exe", "cmd.exe"}
        if proc_name in quiet_processes:
            alerts.append(self._mk(
                "MEDIUM", "T1071", "Application Layer Protocol",
                f"Unexpected outbound connection from '{proc_name}'",
                f"{conn_info.get('laddr')} -> {conn_info.get('raddr')} "
                f"(PID {conn_info.get('pid')})",
                "network",
            ))

        # Identifies connections to ports frequently associated with Command 
        # and Control (C2) frameworks or reverse shells.
        if remote_port in (4444, 1337, 31337, 6666, 8888):
            alerts.append(self._mk(
                "HIGH", "T1071", "Application Layer Protocol",
                f"Connection to commonly-abused port {remote_port}",
                f"{conn_info.get('laddr')} -> {conn_info.get('raddr')} "
                f"(PID {conn_info.get('pid')}, process: {proc_name})",
                "network",
            ))

        return alerts


# ==============================================================================
# Telemetry Collection Mechanisms
# ==============================================================================

def collect_persistence_snapshot() -> dict:
    """
    Aggregates current state data for common OS persistence mechanisms.
    Provides graceful degradation on non-Windows platforms.
    """
    snap = {
        "run_keys": set(),
        "startup_files": set(),
        "scheduled_tasks": set(),
        "services": set(),
    }

    if not IS_WINDOWS:
        return snap

    run_key_paths = [
        (winreg.HKEY_CURRENT_USER, r"Software\Microsoft\Windows\CurrentVersion\Run"),
        (winreg.HKEY_CURRENT_USER, r"Software\Microsoft\Windows\CurrentVersion\RunOnce"),
        (winreg.HKEY_LOCAL_MACHINE, r"Software\Microsoft\Windows\CurrentVersion\Run"),
        (winreg.HKEY_LOCAL_MACHINE, r"Software\Microsoft\Windows\CurrentVersion\RunOnce"),
    ]
    if winreg:
        for hive, subkey in run_key_paths:
            try:
                with winreg.OpenKey(hive, subkey) as key:
                    i = 0
                    while True:
                        try:
                            name, value, _ = winreg.EnumValue(key, i)
                            snap["run_keys"].add(f"{subkey}\\{name} = {value}")
                            i += 1
                        except OSError:
                            break
            except FileNotFoundError:
                pass

    startup_dirs = [
        os.path.expandvars(r"%APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup"),
        os.path.expandvars(r"%PROGRAMDATA%\Microsoft\Windows\Start Menu\Programs\StartUp"),
    ]
    for d in startup_dirs:
        if os.path.isdir(d):
            for f in os.listdir(d):
                snap["startup_files"].add(os.path.join(d, f))

    try:
        out = subprocess.run(
            ["schtasks", "/query", "/fo", "CSV", "/v"],
            capture_output=True, text=True, timeout=20,
        )
        if out.returncode == 0:
            reader = csv.DictReader(out.stdout.splitlines())
            for row in reader:
                name = row.get("TaskName", "")
                if name and "\\Microsoft\\" not in name and row.get("Scheduled Task State") == "Enabled":
                    snap["scheduled_tasks"].add(name)
    except Exception as e:
        print(f"{C.YELLOW}Warning: Scheduled task enumeration failed ({type(e).__name__}: {e}). Results may be incomplete.{C.RESET}")

    try:
        for svc in psutil.win_service_iter():
            info = svc.as_dict()
            if info.get("start_type") == "automatic" and info.get("status") == "running":
                snap["services"].add(f"{info.get('name')} | {info.get('binpath')}")
    except Exception as e:
        print(f"{C.YELLOW}Warning: Windows service enumeration failed ({type(e).__name__}: {e}). Results may be incomplete.{C.RESET}")

    return snap


def collect_processes() -> list:
    """
    Enumerates all currently running processes and retrieves their key attributes.
    Access-restricted processes are silently skipped to prevent collection interruption.

    Returns:
        A list of psutil process info dictionaries (pid, ppid, name, exe, cmdline).
    """
    procs = []
    for p in psutil.process_iter(["pid", "ppid", "name", "exe", "cmdline"]):
        try:
            procs.append(p.info)
        except (psutil.NoSuchProcess, psutil.AccessDenied):
            continue
    return procs


def collect_connections() -> list:
    """
    Enumerates all currently established outbound IPv4/IPv6 network connections.
    Correlates each connection to its owning process name where permissions allow.

    Returns:
        A list of connection dictionaries (pid, process_name, laddr, raddr, remote_port).
        Returns an empty list if system-level access is denied.
    """
    conns = []
    try:
        for c in psutil.net_connections(kind="inet"):
            if c.status != psutil.CONN_ESTABLISHED or not c.raddr:
                continue
            pname = None
            if c.pid:
                try:
                    pname = psutil.Process(c.pid).name()
                except (psutil.NoSuchProcess, psutil.AccessDenied):
                    pname = None
            conns.append({
                "pid": c.pid, "process_name": pname,
                "laddr": f"{c.laddr.ip}:{c.laddr.port}" if c.laddr else None,
                "raddr": f"{c.raddr.ip}:{c.raddr.port}" if c.raddr else None,
                "remote_port": c.raddr.port if c.raddr else None,
            })
    except (psutil.AccessDenied, PermissionError):
        pass
    return conns


# ==============================================================================
# Logging and Alert Management
# ==============================================================================

class AlertLogger:
    """
    Manages the formatting, routing, and persistent storage of generated security alerts.
    Provides support for standard console output, JSON Lines, and CSV log formats.
    """
    def __init__(self, out_dir: str, min_severity: str = "LOW"):
        self.out_dir = Path(out_dir)
        self.out_dir.mkdir(parents=True, exist_ok=True)
        stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        self.json_path = self.out_dir / f"pyedr_alerts_{stamp}.jsonl"
        self.csv_path = self.out_dir / f"pyedr_alerts_{stamp}.csv"
        self.min_severity = SEVERITY_ORDER.get(min_severity, 1)
        self._csv_header_written = False
        self.count = 0
        self.count_by_severity = {k: 0 for k in SEVERITY_ORDER}

    def log(self, alert: Alert):
        """
        Processes a single Alert, routing it to console output and all persistent log files
        if it meets the configured minimum severity threshold.

        Args:
            alert: The Alert object to be logged.
        """
        if SEVERITY_ORDER.get(alert.severity, 0) < self.min_severity:
            return
        alert.print_console()
        self.count += 1
        self.count_by_severity[alert.severity] = self.count_by_severity.get(alert.severity, 0) + 1

        with open(self.json_path, "a", encoding="utf-8") as f:
            f.write(json.dumps(alert.to_dict()) + "\n")

        write_header = not self._csv_header_written
        with open(self.csv_path, "a", newline="", encoding="utf-8") as f:
            writer = csv.DictWriter(f, fieldnames=list(alert.to_dict().keys()))
            if write_header:
                writer.writeheader()
                self._csv_header_written = True
            writer.writerow(alert.to_dict())

    def summary(self):
        """Prints a formatted session summary to the console, including alert counts by severity and log file paths."""
        print(f"\n{C.BOLD}{'=' * 70}{C.RESET}")
        print(f"{C.BOLD}Session Summary: {self.count} alert(s) generated{C.RESET}")
        for sev in ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"]:
            n = self.count_by_severity.get(sev, 0)
            if n:
                print(f"  {SEVERITY_COLOR[sev]}{sev}: {n}{C.RESET}")
        print(f"  JSON Telemetry Log : {self.json_path}")
        print(f"  CSV Telemetry Log  : {self.csv_path}")
        print(f"{C.BOLD}{'=' * 70}{C.RESET}")


# ==============================================================================
# Orchestration and Execution Modes
# ==============================================================================

def run_scan(logger: AlertLogger, engine: DetectionEngine):
    """
    Executes a comprehensive, point-in-time system audit. Evaluates active 
    processes, baseline persistence states, and active network connections.
    """
    print(f"{C.CYAN}{C.BOLD}PyEDR: Initiating comprehensive system scan...{C.RESET}\n")

    process_list = collect_processes()
    print(f"{C.GRAY}Scanning {len(process_list)} running processes...{C.RESET}")
    for p in process_list:
        for alert in engine.evaluate_process(p):
            logger.log(alert)

    print(f"{C.GRAY}Scanning persistence locations...{C.RESET}")
    persistence = collect_persistence_snapshot()
    print(f"{C.GRAY}  {len(persistence['run_keys'])} run-key entries, "
          f"{len(persistence['startup_files'])} startup files, "
          f"{len(persistence['scheduled_tasks'])} non-Microsoft scheduled tasks, "
          f"{len(persistence['services'])} auto-start services{C.RESET}")
    # During initial scans without prior baselines, evaluate against an empty 
    # configuration to surface all current entries as informational context.
    empty = {k: set() for k in persistence}
    for alert in engine.evaluate_persistence_delta(empty, persistence):
        alert.severity = "INFO"  # Downgraded to INFO as this represents inventory state
        alert.title = alert.title.replace("New ", "Existing: ")
        logger.log(alert)

    print(f"{C.GRAY}Scanning active network connections...{C.RESET}")
    for c in collect_connections():
        for alert in engine.evaluate_network(c):
            logger.log(alert)

    logger.summary()
    print(f"\n{C.GRAY}Recommendation: Utilize '--mode agent' for continuous monitoring "
          f"to detect anomalous behavioral events in real-time.{C.RESET}")


def run_agent(logger: AlertLogger, engine: DetectionEngine, interval: int):
    """
    Initializes continuous system monitoring. Establishes a persistence baseline 
    on startup and continuously polls the system at the specified interval to detect:
      - Modifications to persistence mechanisms (differential analysis).
      - Malicious process behavioral indicators (evaluated per newly-spawned PID).
      - Anomalous network communications (evaluated per active connection).
    """
    print(f"{C.CYAN}{C.BOLD}PyEDR: Initializing agent and establishing system baseline...{C.RESET}")
    baseline_persistence = collect_persistence_snapshot()
    print(f"{C.GRAY}Baseline: {len(baseline_persistence['run_keys'])} run keys, "
          f"{len(baseline_persistence['startup_files'])} startup files, "
          f"{len(baseline_persistence['scheduled_tasks'])} tasks, "
          f"{len(baseline_persistence['services'])} services{C.RESET}")

    known_pids = {p["pid"] for p in collect_processes()}
    print(f"{C.GRAY}Baseline: {len(known_pids)} running processes{C.RESET}")
    print(f"{C.GREEN}Agent live. Polling every {interval}s. Ctrl+C to stop.{C.RESET}\n")

    try:
        while True:
            time.sleep(interval)

            # Phase 1: Persistence Differential Analysis
            current_persistence = collect_persistence_snapshot()
            for alert in engine.evaluate_persistence_delta(baseline_persistence, current_persistence):
                logger.log(alert)
            baseline_persistence = current_persistence  # Advance the rolling baseline to the current state

            # Phase 2: Behavioral Evaluation of Newly Spawned Processes
            current_procs = collect_processes()
            current_pids = {p["pid"] for p in current_procs}
            new_pids = current_pids - known_pids
            for p in current_procs:
                if p["pid"] in new_pids:
                    for alert in engine.evaluate_process(p):
                        logger.log(alert)
            known_pids = current_pids

            # Phase 3: Network Behavioral Analysis of Active Connections
            for c in collect_connections():
                for alert in engine.evaluate_network(c):
                    logger.log(alert)

    except KeyboardInterrupt:
        print(f"\n{C.YELLOW}Agent stopped by user.{C.RESET}")
        logger.summary()


# ==============================================================================
# Command Line Interface (CLI) Entry Point
# ==============================================================================

def main():
    """
    Primary entry point for the PyEDR CLI. Parses command-line arguments,
    initializes the detection engine and alert logger, and dispatches
    to the appropriate execution mode (scan or agent).
    """
    C.enable_on_windows()

    parser = argparse.ArgumentParser(
        description="PyEDR: Enterprise Endpoint Detection and Response Agent — MITRE ATT&CK® mapped, transparent, rule-based host monitoring.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python pyedr.py --mode scan
  python pyedr.py --mode agent --interval 15
  python pyedr.py --mode agent --interval 30 --min-severity MEDIUM --out ./logs
""",
    )
    parser.add_argument("--mode", choices=["scan", "agent"], default="scan",
                         help="scan = one-shot deep report; agent = continuous monitoring (default: scan)")
    parser.add_argument("--interval", type=int, default=10,
                         help="agent poll interval in seconds (default: 10)")
    parser.add_argument("--min-severity", choices=list(SEVERITY_ORDER.keys()), default="LOW",
                         help="minimum severity to log/print (default: LOW)")
    parser.add_argument("--out", default="./pyedr_reports",
                         help="output directory for JSON/CSV alert logs (default: ./pyedr_reports)")
    args = parser.parse_args()

    if not IS_WINDOWS:
        print(f"{C.YELLOW}Note: not running on Windows -- registry/service/scheduled-task "
              f"persistence checks will be skipped. Process and network monitoring still work.{C.RESET}\n")

    logger = AlertLogger(args.out, min_severity=args.min_severity)
    engine = DetectionEngine()

    if args.mode == "scan":
        run_scan(logger, engine)
    else:
        run_agent(logger, engine, args.interval)


if __name__ == "__main__":
    main()
